name: Daily Auto Commit

on:
  schedule:
    # Run every day at 05:30 UTC
    - cron: '30 5 * * *'
  workflow_dispatch:  # Optional manual run

jobs:
  auto-commit-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add log line by 23f2004665@ds.study.iitm.ac.in
        run: |
          echo "Updated on $(date -u)" >> daily-log.txt

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "Automated daily update [skip ci]" || echo "Nothing to commit"
          git push
